project_name: camera
session_name: camera
root: /
suppress_history: false
windows:
  - camera:
      layout: tiled
      panes:
        - imx_cameras:
          - udp4-dds-config
          - ros2 launch isaac_ros_main camera_main.launch.py
        - aruco_detections:
          - ls 
        - empty:
          - ls
        - empty:
          - ls